#!/bin/bash

# Make sure we are inside the repository.
cd "${BASH_SOURCE%/*}" &&
cd ../..

scripts_folder=$(pwd)'/utils/'
hook_scripts=("check_tags.sh" "check_cross_ref_images.sh" "check_png_images.sh")

repo_root_path=$(git rev-parse --show-toplevel)

# Look for the added or modified Markdown files
files=($(git diff --name-only origin/master '*/*.md' ':(exclude)$repo_root_path/*.md'))

# Loop over the scripts if the array is not empty
if [[ ${files[@]} ]]; then
  for hook in "${hook_scripts[@]}"; do
    bash $scripts_folder$hook ${files[@]}
    if [ $? -ne 0 ]; then
      exit 1
    fi
  done
fi
